timeout: 5
retry: 2
max_log_days: 30
services:
  - name: "My Pages"
    api:
      - url: "https://qinglong.88830663.xyz"
#      - url: "https://file.ch3nyang.top"
#      - url: "https://til.ch3nyang.top"
#      - url: "https://mind.ch3nyang.top"
#  - name: "My Services"
#    health:
#      - url: "https://docker-registry.ch3nyang.top/health"
#      - url: "https://2024.ch3nyang.top/health"
#    api:
#      - url: "https://docker-registry.ch3nyang.top/v2"
#        status_code: 401
#      - url: "https://2024.ch3nyang.top"
